### ISSUE TITLE
how to create unique dataset

### ISSUE THREAD

**Issue by taktak1** [aik2mlj/diffpro#1]
Thank you for developing such a framework.

What I want to do is learn a unique model using a unique dataset, but how is this possible?

https://github.com/music-x-lab/POP909-Dataset/blob/master/data_process/data_process.ipynb
For example, the file format created in pop909's notebook is npy, not npz.
Also, you are loading the list file when loading the dataset, right?
I don't even know how to make it.

@aik2mlj

**Comment by aik2mlj** [comment]
Hi! I will look into this and try to provide a more convenient way to load custom dataset in the following days!
As for now, you may take a look at the `midi_to_data.py` and `datasample.py` file here:
https://github.com/aik2mlj/polyffusion/blob/sdf_prmat2c%2Bpop909/polyffusion/data/midi_to_data.py
https://github.com/aik2mlj/polyffusion/blob/sdf_prmat2c%2Bpop909/polyffusion/data/datasample.py

They can get a midi file input and transform it into the data format we use in the model!

**Comment by aik2mlj** [comment]
See https://github.com/aik2mlj/polyffusion/pull/3
